all: Program.class

Program.class: BookBrowsing.java UserStats.java BookStats.java BookRecord.java CheckIn.java BookReview.java Connector.java Order.java Book.java Register.java UserRecord.java WaitList.java CheckOut.java NewBook.java SplitAuthors.java AddCopies.java LateList.java 
	javac  BookBrowsing.java UserStats.java BookStats.java BookRecord.java CheckIn.java BookReview.java Connector.java Order.java Book.java Register.java UserRecord.java WaitList.java CheckOut.java NewBook.java SplitAuthors.java AddCopies.java LateList.java

clean:
	rm -f *.class